### ISSUE TITLE
Missing version code bump in new release

### ISSUE THREAD

**Issue by jspricke** [bossly/uaTranslit#11]
The last version 1.2.2 has the same version code (1) as the version before (1.2.1):
https://github.com/bossly/uaTranslit/blob/master/app/build.gradle#L18

please bump the version code with every new release so the Android system recognizes it the release as newer.

This also means that the latest release is not available on F-Droid, so would be great if you could bump the version code and tag a new release.

**Comment by bossly** [comment]
thanks for this issue. I'll resolve it soon
